#!/bin/bash
#NAME: dockemu
#AUTHOR: Marcos Cano  2015
#CONTACT INFO: jmarcos.cano@gmail.com , marcos.cano@galileo.edu
#VERSION: 1.1 
#DESCRIPTION: 




containers=0
docker_image="to_dockemu:simple"


verbose=false


## deberian ser leidas del conf file
#GENERAL
# waf_path=/home/emulation/repos/ns-3-allinone/ns-3-dev/
# logfile="logs/naet.log"
# persistence=true
# container_log_path=log/




# ### OLSRD DEFAULTS
# olsr_containers=2
# olsr_network=10.0.0.0
# olsr_etmask=255.0.0.0


# ###BMX6
# bmx6_containers=2
# bmx6_network=10.0.0.0
# bmx6_netmask=255.0.0.0


version="V.2.0 BETA"

if $verbose;then 
	set -x
fi
# if [[ $USER != "root" ]]; then 
# 		echo "This script must be run as root!" 
# 		exit 1
# fi 


#tools()
#docker logs docker-$id


red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
cyan=`tput setaf 7`
yellow=`tput setaf 3`


                                              

dockemu(){
echo  "${green}##############################################"
echo  "##############################################"
echo  "______ _____ _____  _   __ ________  ____   _ "
echo  "|  _  \  _  /  __ \| | / /|  ___|  \/  | | | |"
echo  "| | | | | | | /  \/| |/ / | |__ | .  . | | | |"
echo  "| | | | | | | |    |    \ |  __|| |\/| | | | |"
echo  "| |/ /\ \_/ / \__/\| |\  \| |___| |  | | |_| |"
echo  "|___/  \___/ \____/\_| \_/\____/\_|  |_/\___/ "
echo  ""
echo  "##############################################"
echo  "#########  WELCOME TO DOCKEMU $version #####"
echo  "##############################################"
echo  ""
echo  "${reset}"
}


dockemu

#######################
# usage()
# script usage
#######################
usage(){

	cat <<-EOU
	${yellow} usage :   $0 [COMMAND] [OPTIONS]  

    Commands:

      start, -s, -start   [config file]                            starts DOCKEMU with a config file  :)

      attach 	[container-ID]                                     attach to a given container, useful to debug
        
      destroy,-d,--d  <all| containerID>                           destroys a containerID or all

      list                                                         list running containers


      print                                                        prints the current configuration


      -help,-h,--help                                              prints this message
	

	NOTE: if no configuration file is provided  while start it will use the default one
	${reset}
	EOU
}



#######################
#attach()
#description:
# attach to a running container
#######################
attach(){
	id=$1
	docker exec -it $id /bin/bash
}

list(){
	echo "AVAILABLE DOCKEMUS"
	docker ps |grep to_dockemu|awk '{print $(NF)}'
}


#######################
# destroy()
# description:
# function to destroy a single container
# or destroy all
#######################
destroy(){

	id=$1
	#destroy containers
	#lxc-destroy -n container-${id}
	###bridge down
		#docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)

	if [ "$id" = "all" ];then
		while read line
		do
		    name=$line
		    echo "Text read from file - $name"
		    destroy $name
		done < logs/running.log
	else
		ifconfig "br-${id}" down #2>/dev/null
		###rm taps from bridges
		brctl delif "br-${id}" "tap-${id}" #2>/dev/null
		###destroy the bridges
		brctl delbr "br-${id}"  #2>/dev/null
		###taps down
		ifconfig "tap-${id}" down  #2>/dev/null
		###delete taps
		tunctl -d "tap-${id}" # 2>/dev/null
		##delete iplink
		ip link del "${id}-A" # 2>/dev/null
		ip link del "${id}-B"  #2>/dev/null

		#delete the sml
		docker stop  dockemu-$id  #2>/dev/null
		docker kill dockemu-$id #2>/dev/null
		docker rm dockemu-$id  #2>/dev/null
	fi
	
}


#######################
# log()
# description:
# a bash utility to log msgs to $logfile
# $1 = message to log
#######################
log(){
	message=$1
	date=$(echo [ $(date +%D-%T) ])
	#echo "logging utility"
	if $logging;then
		echo $date $message | tee -a $logfile
	else
		echo $date $message
	fi
}



#######################
# create()
# description:
# ID = $1 
# note: the number or name of the container and 
# all interfaces linked to it, 
# TYPE = $2
# should contain the type of the container
# i.e: olsrd ,  bmx6
# note: bmx6 or olrsd
#######################
create_bridge(){

echo "bridge"

}

count=1
create(){	
		#read -p ""
		# type=$2
		# if [ ! -z "$type" ];then	
		# 	id=$type-$1
		# else
		# 	id=$1
		# fi

		id=$1
		echo $id >> logs/running.log
		#type=$(echo $id |tr "-" " "|awk '{print $1}')
		
		### SET VARIABLES
		bridge="br-${id}"
		tap="tap-${id}"
		sideA="$id-A"
		sideB="$id-B"
		
		#echo $bridge $tap $sideB $sideA
		
		#make sure everything is destroyed before creating it.
		destroy $id &>/dev/null
		### CREATE OUTER BRIDGES
		brctl addbr $bridge \
		&& tunctl -t $tap \
		&& ifconfig $tap 0.0.0.0 promisc up \
		&& brctl addif $bridge $tap \
		&& ifconfig $bridge up  &>/dev/null

		#echo "outer bridge $bridge created"
		log "BRIDGES: br: $bridge tap: $tap CREATED"

		#EL ID DEBERIA TENER TAMBIEN EL TIPO!!!
		### RUN IT
		#try
		{
			if  $persistence ;then
				
				if [ ! -e $(pwd)/logs/$id/ ];then
					mkdir $(pwd)/logs/$id/
				fi 

				#if [ $count -gt $(($type_count / 2 )) ];then
				#	echo "***********IN THE HALF!!!!!! 10.1.0.0/16"
				#	contain=$(docker run -e "half=1" -e "count=$count" -v $(pwd)/logs/$id/:/var/log/supervisor/ --privileged  -d --net=none --name dockemu-$id $docker_image )

				#else
					contain=$(docker run -e "half=0"  -e "count=$count" -v $(pwd)/logs/$id/:/var/log/supervisor/ --privileged  -d --net=none --name dockemu-$id $docker_image )
				#fi
			else
				contain=$(docker run --privileged -e "count=$count"  -d --net=none --name dockemu-$id $docker_image )
			fi

		#docker run --privileged -i -t -d --net=none --name docker-$id $docker_image -t $type -i $id #&& #2>/dev/null
		#docker run -v $(pwd)/logs:/var/log  --entrypoint /bin/bash --privileged -d  --net=none --name docker-$id $docker_image  -c "/bin/bash"
		#echo "DOCKER: docker-$id CREATED"
			log "DOCKER: docker-$id  ID: $id TYPE: $type CREATED"
		}|| # catch
		{
			echo "DOCKER issues creating docker-$id"
			#exit 0
		}
		

		## CREATE INNER BRIDGE
		pid=$(docker inspect -f '{{.State.Pid}}' dockemu-${id} )
		echo $pid
		mkdir -p /var/run/netns  2>/dev/null
		ln -s /proc/$pid/ns/net /var/run/netns/$pid

		ip link add $sideA type veth peer name $sideB
		brctl addif $bridge $sideA
		ip link set $sideB netns $pid
		ip netns exec $pid ip link set dev $sideB name eth0
		ip netns exec $pid ip link set eth0 up

		

		ip netns exec $pid ip addr add 10.0.0.$count/16 dev eth0   #network???
		ip link set $sideA up

		#log the name of the container and all interfaces attached to it

		## if everything went ok count++
		log "NETWORK inside DOCKER: dockemu-$id IP:10.0.0.$count/16    CREATED & ATTACHED TO BRIDGES"
		count=$((count +1 ))
		log ""

}


#######################
#template()
#description:
# templates the CC file
#######################
template(){
	id=$1
	conteo=$2
	#echo "TEMPLATING" $id

	text="tapBridge.SetAttribute (\"DeviceName\", StringValue (\"tap-${id}\")); \n
  	tapBridge.Install (nodes.Get ($conteo), devices.Get ($conteo));"
  	echo $text
	sed  -i "/running containers/a $(echo $text)" $template_file.cc
}






#######################
#config_reader()
#description:
# reads the config file
#######################
config_reader(){
	echo "##### CONFIG READER: ##### "
	conf_file=$1
	source $conf_file

	lista=$(cat $conf_file|grep -v "#" )
	for i in $lista;do
		echo $i
	done

}

#######################
### start_waf()
## Description:
### copies the .cc file and starts the waf with that .cc
#######################

start_waf(){
	echo "RUNNING SIMULATION press CTRL-C to stop it"
	cp $template_file.cc $waf_path/scratch/tap-csma-virtual-machine-cpy.cc

	current=$(pwd)
	cd $waf_path
	./waf build
	./waf --run tap-csma-virtual-machine-cpy

	cd $current
}

start(){
	
	type=$1
	type_count=$2
	### while OLSRD containers
	echo 
	echo "#####  $type START  ##### "

### CREATE
	j="0"
	list=""
	while [ $j -lt $type_count ]
	do
		echo "STARTING: $type-$j"
		list=$list" $type-$j "
		idi=${type}-$j
		create $idi
		j=$[$j+1]	
	done


### TEMPLATE
	cp $template_file $template_file.cc
	sed -i "s=nodes.Create(2);=nodes.Create($olsr_containers);=" $template_file.cc
	#new thing
	sed -i "s=Simulator::Stop (Seconds (600.));=Simulator::Stop (Seconds ($runningTime.));="  $template_file.cc

	j="0"
	while [ $j -lt $type_count ]
	do
		echo "TEMPLATING: $type-$j"
		id=${type}-$j
		template $id $j
		j=$[$j+1]
	done

	
	echo "RUNNING: $runningTime"

	start_waf

	#sleep $runningTime

	# for i in $list;do
	# 	destroy $i &>/dev/null
	# done

	 echo "KILLING "

	j="0"
	while [ $j -lt $type_count ]
	do
		echo "KILLING: $type-$j"
		id=${type}-$j
		destroy $id
		j=$[$j+1]
	done

	#kill all
	#docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)
}

conf_file=conf/dockemu.conf

if [ $# -gt 0 ] ;then
	
	args=$@
	case $1 in
		start|--start|-start|-s|--s)
			#echo "start"
			rm logs/running.log

			if [ ! -z $2 ];then
				conf_file=$2
				if [ -f $conf_file ];then
					#echo "conf: $conf_file found"
					#step 1:
					#echo "lets read it"
					
					config_reader $conf_file
					#step 2:
					rm /var/run/netns/*
					start olsrd $olsr_containers


				else
					echo "${red}conf file: '$conf_file' NOT FOUND ${reset}"
					exit 0
				fi	
			else
				echo "${red}[ERROR] config file not provided ${reset}"
				usage
			fi
		;;
		destroy|--destroy|-destroy|-d|--d)
			#echo destroy
			if [ ! -z $2 ];then
				echo "destroy"
				
				destroy $2

			else
				echo "${red}[ERROR] destroy all or a specific ID? ${reset}"
				exit 0
			fi
		;;	
		attach|a|-a|--a)

			if [ ! -z $2 ];then
				attach $2
			else
				echo "wrong attach"
				usage
			fi
		;;
		list|ls)

			list
		;;
		help|--help|-h|--h|-help)
				usage
				;;
		print)
			echo " print the current config"
			;;
		*)
		  echo "${red} WRONG OPTION(S) $@ ${reset}"
		usage
		;;
	esac
else
	usage
fi


